name: build

on:
  push:
    branches:
      - master
  pull_request:

env:
  VERSION: v1.0.${{ github.run_number }}${{ fromJSON('["-dev", ""]')[github.ref == 'refs/heads/master'] }}
  REGISTRY: ghcr.io

jobs:
  build:
    name: "Build ${{ matrix.go }}"
    strategy:
      matrix:
        go: ["1.20"]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Go version
      run: go version

    - name: Checkout
      uses: actions/checkout@v3

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -vet=off -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Build binaries
      run: go build

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: "${{ env.VERSION }}"

    - uses: rickstaa/action-create-tag@v1
      if: github.ref == 'refs/heads/master'
      with:
        tag: "${{ env.VERSION }}"
        tag_exists_error: true
        message: "${{ env.VERSION }}"
        github_token: ${{ secrets.GH_TOKEN }}
