name: build

on:
  push:
    branches:
      - master
  pull_request:

env:
  VERSION: 1.0.${{ github.run_number }}${{ fromJSON('["-dev", ""]')[github.ref == 'refs/heads/master'] }}

jobs:
  build:
    name: "Build ${{ matrix.go }}"
    strategy:
      matrix:
        go: ["1.20"]
    runs-on: ubuntu-latest
    steps:
    - name: Set up git
      run: |
        git config --global user.email "release@example.com"
        git config --global user.name "Release Bot"

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Go version
      run: go version

    - name: Checkout
      uses: actions/checkout@v3

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -vet=off -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Build binaries
      run: go build

    - name: Build docker image
      run: docker build -t "${{ env.VERSION }}" .

    # Push the image to the registry
    # ...

    - uses: rickstaa/action-create-tag@v1
      if: github.ref == 'refs/heads/master'
      with:
        tag: "${{ env.VERSION }}"
        tag_exists_error: true
        message: "${{ env.VERSION }}"
